/**
 * Core physical-presence and order session constants.
 */

const DEFAULT_ORDER_SESSION_MINUTES = 90;

const MAX_ACCEPTED_LOCATION_ACCURACY_METERS = 150;

const MIN_ORDERING_RADIUS_METERS = 30;

const MAX_ORDERING_RADIUS_METERS = 200;

module.exports = {
  DEFAULT_ORDER_SESSION_MINUTES,
  MAX_ACCEPTED_LOCATION_ACCURACY_METERS,
  MIN_ORDERING_RADIUS_METERS,
  MAX_ORDERING_RADIUS_METERS
};
