/**
 * Constants for the Core Order System.
 */

const ORDER_ERROR_CODES = {
  ORDER_SESSION_INVALID: 'ORDER_SESSION_INVALID',
  ORDER_SESSION_EXPIRED: 'ORDER_SESSION_EXPIRED',
  ORDER_LOCATION_VERIFICATION_FAILED: 'ORDER_LOCATION_VERIFICATION_FAILED',

  ORDER_MENU_EMPTY: 'ORDER_MENU_EMPTY',
  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',
  MENU_ITEM_UNAVAILABLE: 'MENU_ITEM_UNAVAILABLE',
  MENU_ITEM_RESTAURANT_MISMATCH: 'MENU_ITEM_RESTAURANT_MISMATCH',
  INVALID_ORDER_QUANTITY: 'INVALID_ORDER_QUANTITY',

  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ACCESS_DENIED: 'ORDER_ACCESS_DENIED',

  ORDER_WORKFLOW_PERMISSION_DENIED: 'ORDER_WORKFLOW_PERMISSION_DENIED',
  ORDER_STATE_CHANGED: 'ORDER_STATE_CHANGED',
  ORDER_NO_NEXT_WORKFLOW_STEP: 'ORDER_NO_NEXT_WORKFLOW_STEP',

  ORDER_ALREADY_CLAIMED: 'ORDER_ALREADY_CLAIMED',
  ORDER_CLAIM_NOT_ALLOWED: 'ORDER_CLAIM_NOT_ALLOWED',

  ORDER_CANCELLATION_NOT_ALLOWED: 'ORDER_CANCELLATION_NOT_ALLOWED',

  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  SERVER_ERROR: 'SERVER_ERROR'
};

const SYSTEM_STATES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUSES = {
  UNPAID: 'unpaid',
  PAID: 'paid',
  REFUNDED: 'refunded'
};

const PAYMENT_METHODS = {
  CASH: 'cash',
  CARD: 'card',
  TELEBIRR: 'telebirr',
  OTHER: 'other'
};

module.exports = {
  ORDER_ERROR_CODES,
  SYSTEM_STATES,
  PAYMENT_STATUSES,
  PAYMENT_METHODS
};
